name: escoliosis_detector
description: "Detección local de escoliosis con IA"

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  image: ^4.0.17
  # Forzando la versión compatible con Dart 3
  tflite_flutter: ^0.12.1
  path_provider: ^2.1.1
  provider: ^6.1.2
  sqflite: ^2.3.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/models/ # Carpeta de los modelos
